### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by m-muecke** [fstermann/mlr-mini#11]
# Tasks
- Create Parameter initializer for different types
  - [x] `p_dbl` Double
  - [x] `p_int` Integer
  - [x] `p_fct` Factor
  - [x] `p_lgl` Logical
- [x] Implement `hp` function
  - Should return an object of type `HyperparameterSpace`
  - Contains all given hyperparameters
- [x] Implement printer for `HyperparameterSpace`
- [x] Implement `hyperparameters` function
  -  gets the hyperparamter space `HyperparameterSpace` of a given inducer (or model as well?)
- [ ] Expose `$hyperparameters` attribute in inducer (and model?)
  - Is fetched via the `hyperparamters` function (similar to `coef`)
- Implement `<-.HyperparameterSpace` 
  - to be able to assign a new value to a hyperparameter
- [x] Create `checkHyperparameter(hp, hp.space)` to assert if parameters given as a list lie in the hyperparameter space
  - `hp` List of named args
  - `hp.space` Hyperparameter Space

# Description
The hyperparameter space that is e.g. contained in `InducerXGBoost` are a generally useful concept that should also be represented as `S3` objects.

```r
hpx <- hp(p_dbl(0, 1), p_int(1, 10), p_fct(letters))

hpx
#>    name type                range
#> 1:    x  dbl               [0, 1]
#> 2:    y  int              [1, 10]
#> 3:    z  fct {"a", "b", "c", ...}

checkHyperparameter(list(x = 1, y = 1, z = "a"), hpx)
#> [1] TRUE

checkHyperparameter(list(z = "a"), hpx)
#> [1] TRUE

checkHyperparameter(list(z = "A"), hpx)
#> [1] "Must be element of set {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'}, but is 'A'"

**Comment by fstermann** [comment]
```R
hpx <- hp(p_dbl(0, 1), p_int(1, 10), p_fct(letters))

hpx
#>    name type                range
#> 1:    x  dbl               [0, 1]
#> 2:    y  int              [1, 10]
#> 3:    z  fct {"a", "b", "c", ...}

checkHyperparameter(list(x = 1, y = 1, z = "a"), hpx)
#> [1] TRUE

checkHyperparameter(list(z = "a"), hpx)
#> [1] TRUE

checkHyperparameter(list(z = "A"), hpx)
#> [1] "Must be element of set {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'}, but is 'A'"
```
