### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by fstermann** [fstermann/mlr-mini#3]
# Tasks
- [ ] Implement `Dataset` class generator
  - Arguments
    - `data`
    - `target`
    - Optional: `type` (one of `c("regression", "classification")`, default is NULL or regression?
      - [ ] Fix: Right now, type is the above array, so regression and classification
        - This should either be regression or NULL   
    - Optional: `name` , default is `as.name(deparse(substitute(data), 20)[[1]])`
- [x] Implement printer for `Dataset`
- [x] Implement generic access `[` for `Dataset`
  - `[.Dataset`
- [x] Implement `metainfo()` generic
  - Should be of type `DatasetInfo`
  - `metainfo.Dataset`
 
# Description

Different learning algorithms use datasets in different formats (e.g. `matrix` or `data.frame`) and require different ways of specifying the response / target / outcome data (e.g. through a `formula`, or by having a distinct `label` or `y` argument).

The data, and which part of it should be predicted, is often closely linked.
We will therefore collect this information in one object, which we call `Dataset`.

```r
cars.data <- Dataset(data = cars, target = "dist")
print(cars.data)
#> Dataset "cars", predicting "dist" (Regression)
#>      dist speed
#>     <num> <num>
#>  1:     2     4
#>  2:    10     4
#> ---            
#> 49:   120    24
#> 50:    85    25
class(cars.data)
#> [1] "DatasetRegression" "Dataset"

cars.data[c(1, 2, 3, 4), ]
#> Dataset "cars", predicting "dist" (Regression)
#>      dist speed
#>     <num> <num>
#> 1:      4    2
#> 2:      4   10
#> 3:      7    4
#> 4:      7   22

cars.data[c(1, 2), "dist"]
#> Dataset "cars", predicting "dist" (Regression)
#>      dist
#>     <num>
#> 1:      4
#> 2:      4

cars.data[, "cars"]
#> Error: Cannot remove target column "dist"

metainfo(cars.data)
#> $features
#> speed 
#> "num" 
#> 
#> $targets
#>  dist 
#> "num" 
#> 
#> $nrow
#> [1] 50
#> 
#> $type
#> [1] "regression"
#> 
#> $missings
#> [1] FALSE
#> 
#> attr(,"class")
#> [1] "DatasetInfo"
```

`Dataset()` should have arguments `data` and `target`, as well as an optional argument `type` (one of `"regression"`, `"classification"`) and an optional argument `"name"`, defaulting to `as.name(deparse(substitute(data), 20)[[1]])`.

**Comment by m-muecke** [comment]
Following arguments:

- data
- target
- type (one of "regression", "classification")
- name (optional) defaulting to `as.name(deparse(substitute(data), 20)[[1]])`
